spring:
  application:
    name: ms-tasks
  datasource:
    url: jdbc:mysql:${URI_DB_MS_TASKS}
    username: ${USERNAME_DB_MS_TASKS}
    password: ${PASSWORD_DB_MS_TASKS}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082

eureka:
  client:
    fetch-registry: true

