spring:
  application:
    name: ms-tasks
  datasource:
    url: jdbc:mysql://localhost:3306/tasks
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082

eureka:
  client:
    fetch-registry: true

